# Site settings
course_name: "SIT330-770 - Natural Language Processing"
course_description: "In today's digital age, the pervasive use of technology has transformed the way we communicate, resulting in an unprecedented surge of text data across various platforms. From webpages and social media posts to emails and medical reports, this text-centric communication has created a vast reservoir of information. Companies recognize the immense value embedded in this textual data, making the ability to extract meaningful insights from it crucial for their success. This unit, Natural Language Processing, delves into the core techniques and methodologies designed to harness the power of large-scale text data. Focusing on descriptive, predictive, and prescriptive analytics, the course explores cutting-edge Document Processing techniques. Students will gain in-depth knowledge of fast, effective, and scalable approaches in information retrieval, text mining, and machine learning algorithms."
course_semester: "Trimester 1, 2025"

baseurl: "/2025" # the subpath of your site, e.g. /blog/
url: "https://sit330-770.github.io/" # the base hostname & protocol for your site

schoolname: "Deakin University"
schoolurl: "https://www.deakin.edu.au/"
# twitter_username: username 

address: |
    School of Information Technology
    Deakin University
    Victoria, Australia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
